### ISSUE TITLE
Schema management control need

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/gluon#106]
We need to start including database migration scripts for db changes. Investigate using liquibase for the project.

**Comment by donovanmuller** [comment]
Flyway is potentially simpler. Maybe evaluate asked another option.

**Comment by kbristow** [comment]
Flyway is not database agnostic. Since we are not forcing what database to use, liquibase seems like a better solution. Plus @chriskieser and myself have a probably biased poor history with Flyway ;(
