### ISSUE TITLE
Make Atomist web hook configurable

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/gluon#5]
Currently the atomist web hook url is hard coded wherever it is used. Since this will change depending on the instance we are using this needs to be extracted to a configurable property.

**Comment by donovanmuller** [comment]
Please use [Type-safe Configuration Properties](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) for this.

See [this](http://www.baeldung.com/configuration-properties-in-spring-boot) for context reference.
