### ISSUE TITLE
Removing @Configuration tag from AtomistConfiguration breaks injection

### ISSUE THREAD

**Issue by kbristow** [absa-subatomic/gluon#9]
`@Configuration` tag was removed from AtomistConfiguration so automatic bean creation no longer works. Application will not start correctly.

**Comment by donovanmuller** [comment]
@kbristow you need to add [`@EnableConfigurationProperties(AtomistConfiguration.class)`](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties) on https://github.com/absa-subatomic/gluon/blob/1e4dabbf1f57c2f2eb46d31a6434bd3cc13ba278/nucleus/src/main/java/za/co/absa/subatomic/infrastructure/NucleusConfigurarion.java#L13
